src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 * @Vich\Uploadable
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @ORM\Column(type="datetime")
     * 
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @Assert\DateTime() 
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @Assert\DateTime() 
     * @Assert\GreaterThan(propertyPath="start_date")
     */
    private $end_date;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\Positive
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $category;


    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime() 
     * @Assert\NotBlank()
     */
    private $beginning_hour;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime() 
     * @Assert\NotBlank()
     */
    private $end_hour;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $archive;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $filename;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="event", fileNameProperty="fileName")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $put_forward;

    /**
     * @ORM\ManyToOne(targetEntity=Location::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $location;

    /**
     * @ORM\ManyToMany(targetEntity=Artiste::class, inversedBy="events")
     */
    private $artiste;

    /**
     * @ORM\ManyToMany(targetEntity=Order::class, mappedBy="event")
     */
    private $orders;

    // /**
    //  * @ORM\Column(type="integer", nullable=true)
    //  */
    // private $child_price;

    public function __construct()
    {
        $this->artiste = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }


    public function getBeginningHour(): ?\DateTimeInterface
    {
        return $this->beginning_hour;
    }

    public function setBeginningHour(\DateTimeInterface $beginning_hour): self
    {
        $this->beginning_hour = $beginning_hour;

        return $this;
    }

    public function getEndHour(): ?\DateTimeInterface
    {
        return $this->end_hour;
    }

    public function setEndHour(\DateTimeInterface $end_hour): self
    {
        $this->end_hour = $end_hour;

        return $this;
    }

    public function getArchive(): ?bool
    {
        return $this->archive;
    }

    public function setArchive(?bool $archive): self
    {
        $this->archive = $archive;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

     /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Livre
     */
    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;
        return $this;
    }

    public function getPutForward(): ?bool
    {
        return $this->put_forward;
    }

    public function setPutForward(?bool $put_forward): self
    {
        $this->put_forward = $put_forward;

        return $this;
    }

    public function getLocation(): ?location
    {
        return $this->location;
    }

    public function setLocation(?location $location): self
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return Collection|artiste[]
     */
    public function getArtiste(): Collection
    {
        return $this->artiste;
    }

    public function addArtiste(artiste $artiste): self
    {
        if (!$this->artiste->contains($artiste)) {
            $this->artiste[] = $artiste;
        }

        return $this;
    }

    public function removeArtiste(artiste $artiste): self
    {
        $this->artiste->removeElement($artiste);

        return $this;
    }

    // public function getChildPrice(): ?int
    // {
    //     return $this->child_price;
    // }

    // public function setChildPrice(?int $child_price): self
    // {
    //     $this->child_price = $child_price;

    //     return $this;
    // }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->addEvent($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            $order->removeEvent($this);
        }

        return $this;
    }
}

templates/front/events.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('events') }}
    <link href="/build/events.css" rel="stylesheet">
{% endblock %}
{% block body %}

    {% include "parts/_header.html.twig" with {'title': title}%}

    <main>
        <div id="filter-menu">
            
        <button id="filter-button" ><i class="fa fa-sliders" aria-hidden="true"></i></button>
            <div id="filter-options">
                <div id="search-form">
                    
                    
                    {{ form_start(form)}}
                    

                    {# <div id="form-search"> 
                        <i class="fa fa-search" aria-hidden="true"></i>{{ form_row(form.q)}} 
                    </div> #}

                    <div id="form-cat">
                        {{ form_row( form.category)}}
                        
                    </div>

                    <div id="form-price">
                        {{ form_row(form.min)}}
                        {{ form_row(form.max)}}
                    </div>

                    <button id="form-submit" type="submit">Filtrer </button>

                    {{ form_end(form, {'render_rest': false}) }}
                </div>
            </div>
        </div>

        <section>

        {% if events is empty %}
        <p class="msg-erreur">Aucun résultat ! Modifier votre recherche !</p>
        {% endif %}
        {# <p>{{events.items|length}} Résultats</p>
        {% endif %} #}
        
   
            
            <div id="events">
            
            
            {% for event in events %}
                
                <a href="{{ path ('singleEvent',{ id: event.id} )}}">
                    <div class="single-event">
                        <div class="event-img" style="background-image: url(/pictures/events/{{ event.filename }})">
                        </div>

                        <div class="event-content">
                            <h3>{{ event.title }}</h3> 
                            <p>{{ event.startDate|date('d/m/Y') }} </p>
                            <p>{{ event.location.city}}</p>
                            <p>{{ event.category.label}}</p>
                        </div>
                        
                        
                    </div>
                </a>

            {% endfor %}
            
                
            </div>

            <div>{{ knp_pagination_render(events) }}</div>
            
        
        </section>
        
    </main>
    {% include "parts/_footer.html.twig"%}

    {% block javascript %}
        {{ encore_entry_script_tags('events') }}
        <script type="text/javascript" href="build/events.js"></script>
    {% endblock %}
{% endblock %}

templates/front/home.html.twig
{% extends "base.html.twig" %}

{% block stylesheets %}
    {{ encore_entry_link_tags('homepage') }}
    <link href="/build/homepage.css" rel="stylesheet">
{% endblock %}

{% block body %}

    {% include "parts/_header.html.twig" with {'title': title}%}
<main>
    <div id="slider-div">
        <div id="slider">
            <div id="slider-items">
            {% for event in events %}
                 
                    <div id="slide-img"class="slide" style= "background-image: url(/pictures/events/{{ event.filename }})">
                    <a href="{{ path('singleEvent', {id: event.id} ) }}"> 
                        <h3>{{ event.title }}</h3>
                        <p>{{ event.startDate|date('d/m/Y') }}</p>
                        </a> 
                    </div>
                 
            {% endfor %}
                {# <div id="first-slide" class="slide" style= "background-image: url('pictures/site/concert.jpg')"></div>
                <div id="second-slide" class="slide" style= "background-image: url('pictures/site/concert.jpg')"></div>
                <div id="third-slide" class="slide" style= "background-image: url('pictures/site/concert.jpg')"></div> #}
            </div> 
        </div>
        <i class="fa fa-caret-left" id="slide-left" aria-hidden="true"></i>
        <i class="fa fa-caret-right" id="slide-right"aria-hidden="true"></i>
    </div>
    <div>
        {# <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus libero quam, at aliquet elit scelerisque non. Nam venenatis feugiat auctor. Praesent et urna erat. Etiam enim magna, tincidunt ut urna eu, venenatis posuere risus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus semper sollicitudin orci lacinia ultricies. Mauris a mollis orci. Integer id egestas dolor.</p> #}
    </div>

    <section id="section-category">
        
        <div id="div-category">
            <a href="">
                <div id="card-concert"class="card">
                    <p>Concert</p>
                    <!-- <img src="/pictures/site/concert.jpg" alt="Image-concert"></img> -->
                </div>
            </a>
            <a href="">
                <div id="card-festival"class="card">
                    <p>Festival</p>
                    <!-- <img src="/pictures/site/festival.jpg" alt="Image-festival"></img> -->
                </div>
            </a>
            <a href="">
                <div id="card-spectacle"class="card">
                    <p>Spectacle</p>
                </div>
            </a>
            <a href="">
                <div id="card-sport"class="card">
                    <p>Sport</p>
                </div>
            </a>
        </div>
       
    </section>
</main>
    {% include "parts/_footer.html.twig"%}

    {% block javascript %}
        {{ encore_entry_script_tags('homepage') }}
        <script type="text/javascript" href="build/homepage.js"></script>
    {% endblock %}
{% endblock %}

templates/front/login.html.twig
{% extends "base.html.twig" %}
{% block stylesheets %}
    {{ encore_entry_link_tags('login') }}
    <link href="/build/login.css" rel="stylesheet">
{% endblock %}
{% block body %}

    {% include "parts/_header.html.twig" with {'title': title}%}
<main>

    <div id="div-login">
        <form id="register-form" class="hidden">
            <h2>S'inscire:</h2>
            <input type="text" placeholder="Adresse mail"/>
            <input type="password" placeholder="Mot de passe"/>
            <button>Créér</button>
            <p id="trigger-login" class="message">Déja inscrit? <span>Connexion</span></p>
        </form>
        <form id="login-form">
            <h2>Se connecter:</h2>
            <input type="text" placeholder="Email"/>
            <input type="password" placeholder="Mot de passe"/>
            <button>Connexion</button>
            <p id="trigger-register"class="message">Pas encore inscrit? <span>Créer un compte</span></p>
        </form>
  </div>

</main>

{% include "parts/_footer.html.twig"%}

    {% block javascript %}
        {{ encore_entry_script_tags('login') }}
        <script type="text/javascript" href="build/login.js"></script>
    {% endblock %}

    
{% endblock %}

templates/front/singleEvent.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block stylesheets %}
    {{ encore_entry_link_tags('singleEvent') }}
    <link href="/build/singleEvent.css" rel="stylesheet">
{% endblock %}
{% block body %}

{% include "parts/_header.html.twig" with {'title': title}%}
<main>  
    <section>
    {% for event in event %}
        <div id="event">
            
            <div id="event-img">
                <img src="/pictures/events/{{ event.filename }}"/>
            </div>
            <div id="event-content">
                <h2>{{event.title}}</h2>
                <p><i class="fa fa-file-text" aria-hidden="true"></i> Voir la description</p>
                <p>
                    <i class="fa fa-calendar" aria-hidden="true">
                    </i> Du {{ event.startDate|date('d/m/Y') }} au {{ event.endDate|date('d/m/Y')}}
                </p>
                <p>
                    <i class="fa fa-map-pin" aria-hidden="true"></i>
                    {{event.location.place}}, <span id="adress">{{event.location.adresse}}, {{event.location.city}} </span>
                </p>
                    
            </div>
        </div>
    
        {% if app.user %}
            <form id="order" method="GET" action="{{ path ('cart_manage', { 'id' : event.id  })}}">
            <input type="hidden" id="adultPrice" value="{{ event.price }}"/>
            {# <input type="hidden" id="childPrice" value="{{event.childPrice }}"/> #}
            <div>
                
                <label for="adult">Tarif: {{ event.price }}€</label>
                <input id="adult" name="number" type="number" required min="0" value="0"/>
            </div>
            {# <div>
                
                <label for="child">Tarif Enfant: {{ event.childPrice }}€</label>
                <input id="child" name="child" type="number" required min="0" value="0"/>
            </div> #}

            <p> Total : <span id="total"> </span> </p>
            
               <a href=""><button id="order-button">Valider</button></a>
            </form>
            
            
            

        
        {% else %}
            <a href="{{ path('app_login')}}"><p class="msg-erreur">Connecter vous pour réservez vos billets !<p></a>
        {% endif %}

        <div id="event-desc">
                <p>{{ event.description}}</p>
        </div>
        <div>
            {% for artiste in event.artiste %}
            
            <p>{{ artiste.name }}</p>
            {% endfor %}
        </div>

        <div id="map"></div>
        {% endfor %}
        
    </section>
</main>
 {% include "parts/_footer.html.twig"%}
 {% block javascript %}
        {{ encore_entry_script_tags('singleEvent') }}
        <script type="text/javascript" href="build/singleEvent.js"></script>
         <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
    {% endblock %}

{% endblock %}